USE [enter_db_name_here]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_QRTZ_EXECUTION_HISTORY_VETOED]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES] DROP CONSTRAINT [DF_QRTZ_EXECUTION_HISTORY_VETOED]
END
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_QRTZ_EXECUTION_HISTORY_RECOVERING]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES] DROP CONSTRAINT [DF_QRTZ_EXECUTION_HISTORY_RECOVERING]
END
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]') AND name = N'IX_TRIGGER_NAME_ACTUAL_FIRE_TIME_UTC')
DROP INDEX [IX_TRIGGER_NAME_ACTUAL_FIRE_TIME_UTC] ON [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]') AND name = N'IX_SCHED_NAME')
DROP INDEX [IX_SCHED_NAME] ON [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]') AND name = N'IX_JOB_NAME_ACTUAL_FIRE_TIME_UTC')
DROP INDEX [IX_JOB_NAME_ACTUAL_FIRE_TIME_UTC] ON [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]') AND name = N'IX_ACTUAL_FIRE_TIME_UTC')
DROP INDEX [IX_ACTUAL_FIRE_TIME_UTC] ON [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QRTZ_EXECUTION_HISTORY_STATS]') AND type in (N'U'))
DROP TABLE [dbo].[QRTZ_EXECUTION_HISTORY_STATS]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]') AND type in (N'U'))
DROP TABLE [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES](
	[FIRE_INSTANCE_ID] [nvarchar](140) NOT NULL,
	[SCHEDULER_INSTANCE_ID] [nvarchar](200) NOT NULL,
	[SCHED_NAME] [nvarchar](120) NOT NULL,
	[JOB_NAME] [nvarchar](150) NOT NULL,
	[TRIGGER_NAME] [nvarchar](150) NOT NULL,
	[SCHEDULED_FIRE_TIME_UTC] [datetime] NULL,
	[ACTUAL_FIRE_TIME_UTC] [datetime] NOT NULL,
	[RECOVERING] [bit] NOT NULL,
	[VETOED] [bit] NOT NULL,
	[FINISHED_TIME_UTC] [datetime] NULL,
	[EXCEPTION_MESSAGE] [nvarchar](max) NULL,
 CONSTRAINT [PK_QRTZ_EXECUTION_HISTORY_ENTRIES] PRIMARY KEY CLUSTERED 
(
	[FIRE_INSTANCE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QRTZ_EXECUTION_HISTORY_STATS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[QRTZ_EXECUTION_HISTORY_STATS](
	[SCHED_NAME] [nvarchar](120) NOT NULL,
	[STAT_NAME] [nvarchar](120) NOT NULL,
	[STAT_VALUE] [bigint] NULL,
 CONSTRAINT [PK_EXECUTION_HISTORY_STATS] PRIMARY KEY CLUSTERED 
(
	[SCHED_NAME] ASC,
	[STAT_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]') AND name = N'IX_ACTUAL_FIRE_TIME_UTC')
CREATE NONCLUSTERED INDEX [IX_ACTUAL_FIRE_TIME_UTC] ON [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]
(
	[ACTUAL_FIRE_TIME_UTC] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]') AND name = N'IX_JOB_NAME_ACTUAL_FIRE_TIME_UTC')
CREATE NONCLUSTERED INDEX [IX_JOB_NAME_ACTUAL_FIRE_TIME_UTC] ON [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]
(
	[JOB_NAME] ASC,
	[ACTUAL_FIRE_TIME_UTC] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]') AND name = N'IX_SCHED_NAME')
CREATE NONCLUSTERED INDEX [IX_SCHED_NAME] ON [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]
(
	[SCHED_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]') AND name = N'IX_TRIGGER_NAME_ACTUAL_FIRE_TIME_UTC')
CREATE NONCLUSTERED INDEX [IX_TRIGGER_NAME_ACTUAL_FIRE_TIME_UTC] ON [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES]
(
	[TRIGGER_NAME] ASC,
	[ACTUAL_FIRE_TIME_UTC] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_QRTZ_EXECUTION_HISTORY_RECOVERING]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES] ADD  CONSTRAINT [DF_QRTZ_EXECUTION_HISTORY_RECOVERING]  DEFAULT ((0)) FOR [RECOVERING]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_QRTZ_EXECUTION_HISTORY_VETOED]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[QRTZ_EXECUTION_HISTORY_ENTRIES] ADD  CONSTRAINT [DF_QRTZ_EXECUTION_HISTORY_VETOED]  DEFAULT ((0)) FOR [VETOED]
END
GO